blank_issues_enabled: true
contact_links:
  - name: ğŸ“š Documentation
    url: https://github.com/skarllot/jab-modules#guide
    about: Read our documentation.
  - name: â­ Sponsor Raiqub Jab Modules
    url: https://www.buymeacoffee.com/skarllot
    about: Help the continued development.
  - name: ğŸ’¬ Ask on Github Discussions
    url: https://github.com/skarllot/jab-modules/discussions
    about: The best place for asking general purpose questions.
